### ISSUE TITLE
Link detection in multiline label

### ISSUE THREAD

**Issue by stigi** [AliSoftware/OHAttributedLabel#10]
Hi,

just stumbled upon this:

I have a label which I created like this

```
OHAttributedLabel *label = [[OHAttributedLabel alloc] initWithFrame:CGRectMake(40, 40, 400, 100)];
NSMutableAttributedString *string = [NSMutableAttributedString attributedStringWithString:@"Th\niii\ns is a test http://google.de?q=test+two"];
label.attributedText = string;
label.numberOfLines = 0;

[label addCustomLink:[NSURL URLWithString:@"http://google.com?q=test+one"] inRange:NSMakeRange(3, 8)];
```

When I click on http://google.de?q=test+two it opens http://google.com?q=test+one.
I'm pretty sure something isn't right in -linkAtPoint.

Some things that look suspicious:
- The height of a line is it's ascent + its descent. In the method only the Ascent from `CTLineGetTypographicBounds` is used
- The flipping of the coordinates is done in a confusing way.

I'll try to fix this and make the code a bit more readable. Maybe we can use code like this https://gist.github.com/966511 to make the flipping of coordinates more readable. (Please have a look if I made any mistake while writing those two methods :))

**Comment by AliSoftware** [comment]
The computation of the coordinates in linkAtPoint may be confusing but I think your methods for flipping the coordinates will make things less readable actually, don't you? We may better apply a CGAffineTransform to the context before our computations instead ?

**For the descent** you may be right. I think there was a reason i didn't use the descent but I can't remember why.
Check http://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/FontHandling/Tasks/GettingFontMetrics.html if you need to identify the different values for a font metric (this is for Mac but i guess the same is for iOS)
The most confusing thing is that the coordinates are not all in the same coordinate space, the one in CoreText being flipped.

**For your problem with your two links**, maybe it is because of the kVMargin I added to take into account that in small texts we never hit the link in the exact position of the link itself. Thus, the rectangle used for detecting the links check the CTLines in order and take a margin of kVMargin at the top and at the bottom of the CTLine typographic bounds, so that the touch is still considered on the link even 5 pixels below or above the link.

**Try reducing kVMargin to zero** and test again to check if this is the real cause of the behavior your remarked.
If it is, a solution would be to consider the case in kVMargin as a special case:
- if the touch is exactly in the typigraphc bounds, then you have a match and return it
- if the touch is not exactly in the typo bounds BUT in the rect consisted by the bounds+ kVMargin, then you have a _potential_ match. Store it in a local variable but continue looping thru the CTLines
- if you reach the end of the loop and haven't found a match, return the potentialMatch variable if one has been found.

**Another optimization in the linkAtPoint algorithm**, that I though about but didn't implement, would be to stop the loop if the Y of the CTLine is way past the Y of the UITouch. Thus if we tap on the top of the label, and the label has 100 lines, don't bother to check for the lines at the bottom, stop the loop after we passed a CTLine that has its top under the Y of the touch.

I hope you got aspirin for this parts of the algorithm if you intend to implement it all :D

**Comment by stigi** [comment]
There's even more wrong in `-linkAtPoint:`. If a line is only 3 characters wide but the click happens to the right of the furthest character `CTLineGetStringIndexForPosition` returns the index of the furthest character.

I created a proposal for a fix in https://github.com/nxtbgthng/OHAttributedLabel/commit/a399b4450cc62ca2021eccd3206803c07490c296

I don't think we need that much optimization in the code since it's not called that often (i.e. not from `-drawRect`). The only thing we should optimize for are very long texts.

And yes, you're right. Flipping coordinate systems is always a hassle. But the more important it is to make super clear when we're dealing with flipped coordinates and when not.

I got to admit my head is aching a bit now :)

**Comment by AliSoftware** [comment]
Warned you about the aspirin :P
I began to having an headache too, will need to read your code later after some rest before merging it ;)

Thanks for your work on this anyway! Will let you know when the merge is done

**Comment by stigi** [comment]
I updated the proposed fix so it applies after #12 (Highlighting of touched link 2)

**Comment by AliSoftware** [comment]
Hi @stigi

I am a bit confused here: should I merge this fix f120921654b7b2360982ae28e81faf683919edca with my repository too (by myself), or was it already included in your last pull request 12 I recently merged and should I ignore this?

If I check the graph at https://github.com/AliSoftware/OHAttributedLabel/network it seems that your "proposed fix for issue #10" was done **after** the pull request, so I would say need to merge it with my own repo as it was not included in the pull request… But as I see the code of this proposed fix, it seems not compatible with what you've done in pull request #12, especially extracting the functions `CTLineGetTypographicBoundsAsRect` and so on… which you don't use in this "proposed fix"

I think I should simply ignore this "proposed fix" above as it seems integrated with the last code, but then why does it still appears in the github network graph?
Are you able to clarify this for me?

Thanks

**Comment by stigi** [comment]
f120921654b7b2360982ae28e81faf683919edca is meant to be merged after pulling #12.

I took the original fix (a399b4450cc62ca2021eccd3206803c07490c296) and rebased it on top of 25ba56589fa4c19cd21eb989f22f6b9ddee436ba (the head for pull request #12) so it applies nicely. The result was f120921654b7b2360982ae28e81faf683919edca.

**Comment by AliSoftware** [comment]
Ok I will merge it then during the week.
What I don't really understand is that your code in f120921654b7b2360982ae28e81faf683919edca, that should be the last version of your repository or so, contains such code:

```
CGFloat lineAccent = 0;
CGFloat lineDecent = 0;
CGFloat lineLeading = 0;
CGFloat lineWidth = CTLineGetTypographicBounds(line, &lineAccent, &lineDecent, &lineLeading);
CGFloat lineHeight = lineAccent + lineDecent;
```

so you don't use your function `CTLineGetTypographicBoundsAsRect` ?! That's why I was wondering if it really was the last version of the fix.

**Comment by stigi** [comment]
Oh I see. I just did the rebase and didn't alter the code. But let me review the entire code to bring it to speed with the helper methods.

**Comment by AliSoftware** [comment]
Ah ok, that makes sense. Cool then :)
I'm waiting for your refactoring then before merging.

I will probably work on issues #13 and #14 during the week (a bit busy the two next days but will have some free time then). Unless of course if you are already working on this? (avoiding conflicts is better ^^)

**Comment by AliSoftware** [comment]
I applied your fix in my own branch, remplacing the lines quoted above with a call to your helper method `CTLineGetTypographicBoundsAsRect`.
Hope I did use it right (based on my tests it seems to be ok but feel free to check).

If everything is ok we may merge our forks/branches so that we are still in sync.

**Comment by AliSoftware** [comment]
Hi @stigi :) wassup?

Any news on this? I am waiting for your code review to close this issue (I don't like having open issues ^^) to be sure I use your helper methods correctly :) So I hope you will have some time for this ;-)

Thx

**Comment by stigi** [comment]
Hey there,
Sorry for not getting back to you earlier. It was the week of my 30th birthday and 1 week before WWDC and holiday, so everything was quite packed.
I had a look at the code and everything looks good now :)

Thanks for merging in all the stuff!
I also had a look at some of the alternative AttributedString labels (FontLabel, RTLabel, CoreTextHyperlinkView) and I gotta say I like OHAttLabel the best :)

**Comment by AliSoftware** [comment]
Great

Thanks for the feedback and the comparison :)
Have a great WWDC
