### ISSUE TITLE
Can I setLink for an url?

### ISSUE THREAD

**Issue by zzndino** [AliSoftware/OHAttributedLabel#106]
I need to display a link like:
sitename.com/abc.html
on OHAttributedLabel. And I want to setLink for this url like:
userlink:sitename.com/abc.html

Then I click the link on label, return twice click action on UIWebView delegate, one with the URL, and the other one without URL....

What shall I do?

**Comment by AliSoftware** [comment]
You probably mean the `OHAttributedLabelDelegate` and not the `UIWebViewDelegate`, right?

Simply disable the automatic detection for links on your `OHAttributedLabel` instance (`lbl.automaticallyAddLinksForType = 0`) so that the link to `http://sitename.com/abc.html` isn't added automatically. Then you can add your own link either to the `OHAttributedLabel` using `addCustomLink:inRange:` (former method)  or add it to the `NSAttributedString` directly using `setLink:range:` (recommended method recently added in latest versions of `NSAttributedString+Attributes.h`, so that the link is attached to the attributed string and not the label that displays it)
