### ISSUE TITLE
Bold effect not taking effect in the table view demo

### ISSUE THREAD

**Issue by ghost** [AliSoftware/OHAttributedLabel#107]
1. It look like the bold effect on _now_ for the entry string @"Visit http://www.apple.com _now_!" is not taking in account. Anyone observing the same issue on his side?
2. What is the recommended way to set a bold effect for a substing in a string of a custom type within a tableview?

I have tried this within my -(UITableViewCell*)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath method:

```
NSMutableAttributedString *attrText =  [OHASBasicMarkupParser attributedStringByProcessingMarkupInString: @"Try *me*!"];
[attrText setFont:[UIFont fontWithName:@"ZagRegular" size: 19]];
[attrText setTextAlignment:kCTLeftTextAlignment lineBreakMode:kCTLineBreakByWordWrapping];
attrLabel.attributedText = attrText;
```

with attrLabel of type: OHAttributedLabel but i don't see again the bold effect. Might be related to the issue 1 or am i doing something wrong here?

**Comment by AliSoftware** [comment]
For the second point, it is totally normal that you don't see any bold font on the "me" text.

This is because to make some text in bold, you have to change the font to the bold variant of the font (namely change the font from, say, `HelveticaNeue` to `HelveticaNeue-Bold`).

But what your code did is that it applied the markup around the `*me*` word, changing its font to bold as you expected… but then you changed the font of the whole string back to `@"ZagRegular"`, thus resetting the font of the whole string to some regular font. That's why the word "me" isn't bold anymore at that point.

You should set your font on your `NSMutableAttributedString` **first**, and **only after** use `processMarkupInAttributedString:` to apply the bold variant then.

**Comment by AliSoftware** [comment]
For the first point, the message in the console should give you the answer:

> [OHAttributedLabel] Warning: can't find a bold font variant for font .Helvetica NeueUI. Try another font family (like Helvetica) instead.

I should have chosen another font instead (i.e. one that has a bold variant). WIll fix that soon.

**Comment by ghost** [comment]
Hi - thanks for taking time to get back to me! I managed to make it work the way i wanted to by indeed  changing the font to its bold variant. Thanks again!
