### ISSUE TITLE
Line padding

### ISSUE THREAD

**Issue by ghost** [AliSoftware/OHAttributedLabel#109]
Is there a way to use this control to add padding to a few lines? I want create an indentation to the right.

**Comment by AliSoftware** [comment]
This is a feature related to `NSAttributedString` directly and has nothing really to do with `OHAttributedLabel` directly.

You can add an indentation for the first line of your paragraphs of you `NSAttributedString` using a `CTParagraphStyleSetting` and the `kCTParagraphStyleSpecifierFirstLineHeadIndent` constant, quite like it is done in the `setTextAlignment:lineBreakMode:range:` method of `NSAttributedString+Attributes.m`. See [here in the documentation](https://developer.apple.com/library/ios/#documentation/Carbon/Reference/CTParagraphStyleRef/Reference/reference.html) for more info too.

_(Note: if you compile for iOS6 only, you may be able to use its Objective-C counterpart `NSParagraphStyle` instead, which is easier to use. But if your application needs to work on iOS prior to iOS6 you still need to use `CTParagraphStyleSetting` and the CoreText functions as the `NSParagraphStyle` class was added in iOS6 only)_

Be careful if you change the `CTParagraphStyle` of your `NSAttributedString` to add this attribute for line indentation, setting a new `CTParagraphStyle` will obviously override the active one if any, so be careful not to override other paragraph settings like text alignment and linebreakMode.

**Comment by AliSoftware** [comment]
Just added this feature in the latest commit. Now you can set all the style attributes of paragraph easily using the `OHParagraphStyle` wrapper, including line spacing and first line and other lines indentation. Don't hesitate to give me some feedback.

**Comment by ghost** [comment]
Wow, awesome. Thanks. 

Say I have this.

``` objc
OHParagraphStyle *style = [[OHParagraphStyle alloc] init];
style.headIndent = 50;
[string setParagraphStyle:style range:NSMakeRange(0, string.length)];
```

This sets an indent for all lines except the first line. Would it not be better to use the headIndent when the firstLineHeadIndent has not been set?

The reason I don't just set firstLineHeadIndent as the same as headIndent is I don't know when certain ranges will be the first line. Sometimes I will want a firstLineIndent and sometimes I won't. For example - when having the first four lines indented I would have to set both firstLineIndent and headIndent.

Or is it a case of having to determine myself whether the range contains the first line and setting firstLineHeadIndent?

**Comment by AliSoftware** [comment]
I am not sure I understand your problem. All this behavior is the same as in any word processor application. **You don't have to know at all "when certain ranges will be the first line"** !!

Maybe you don't understand the concept of "paragraphs" in the sense of CoreText does?

Each time you start a new paragraph (paragraphs are separated by each other with `\n` of course, you know that right?), the first line will be indented with the `firstLineHeadIndent` and all other lines of the same paragraph will be indented with the `headIndent`. When you encounter an `\n` and thus start a new paragraph, the next line will be indented as `firstLineHeadIntent` again, and the following lines in this same second paragraph will be indented as `headIndent`, until the end of the paragraph and the beginning of a new paragraph, etc.

---

Note that some questions in your previous answer are not making sense to me:
- Creating a rule to "use the `headIndent` when the `firstLineHeadIndent` has not been set" does not make any sense. What if I want to indent every line of my paragraph except the first then? I will keep the value of `firstLineHeadIndent` unchanged so that it is set to `0`, so how can we make the difference between "`firstLineHeadIndent` not being set so use `headIndent` instead" and "`firstLineHeadIndent` set to `0` because we don't want to indent the first line"?
- Besides, I don't see how "using `headIndent` when the `firstLineHeadIndent` has not been set" would anyhow solve your problem. Adding such a rule would simply use the value of `50` for all lines including the first, so it won't make any distinction between the case when you have four lines and cases when you have more or less lines.
- If you wanted your paragraphs that are less than 4 lines to have their first line indented, and paragraphs with more that 4 lines not to have indentation for their first line, that wouldn't make any sense either. Because one paragraph that can fit in 4 lines if you don't indent the first line may need 5 lines to be displayed if you add some indent on the first line and that it shifts all the words and the layout of your paragraph.

Normally all you have to do is to set the values of `firstLineHeadIndent` and `headIndent` as you wish and then start new paragraphs when you want a new paragraph with its first line having the `firstLineHeadIndent` indentation. Exactly like in any word processor application like Word or Pages.

---

Just to be clear about how `OHParagraphStyle` works:
- I don't control the interpretation of the paragraph style. All those features I added with `OHParagraphStyle` is just another wrapper around the existing CoreText attributes of `NSAttributedString` that the CoreText layout engine interpret by itself to add indents and all.
- I am not controlling the layout of the words (the `CTFrameSetter` object of the CoreText framework does that for us) so the only thing that is done here is to add attributes to your `NSAttributedString`, so that the CoreText FrameSetter will layout the words according to those attributes. I am not interpreting the attributes to layout the paragraphs, CoreText does.
- In fact, `OHParagraphStyle` is the equivalent of the `NSParagraphStyle` class that Apple added in iOS6: I created the `OHParagraphStyle` class so it can be used in iOS versions prior to iOS6, but it is just a wrapper around the `CTParagraphStyle` C structure used by CoreText.
