### ISSUE TITLE
sizeConstrainedToSize: with setLinkUnderlineStyle:kOHBoldStyleTraitSetBold bug

### ISSUE THREAD

**Issue by ghost** [AliSoftware/OHAttributedLabel#110]
When using `[attrStr sizeConstrainedToSize:constraint]` there seems to be an issue in combination with `setLinkUnderlineStyle:kOHBoldStyleTraitSetBold` I'm using this to calculate the sizes of my UITableViewCells, but the height gets calculated incorrectly.

When setting it to underline or none the calculation is no problem, but from the moment you use the **kOHBoldStyleTraitSetBold** it seems to trim of the new lines

e.g `www.apple.com/
store` becomes `www.apple.com/`
or `www.google.com is a
search engine` becomes `www.google.com is a`, even though it sets the font to bold and it does something weird with the height

**Comment by AliSoftware** [comment]
Hi,

The problem you are having is not an issue of `OHAttributedLabel`, but is because you compute the size of your `NSAttributedString` **without** the links being formatted in bold. In fact, **you compute the size of your original `NSAttributedString` (`attrStr`), not the one reformatted by `OHAttributedLabel` after it has applied the bold link style**.

When you set the `linkUnderlineStyle` property of your `OHAttributedLabel`, it modifies the **copy** of the `NSAttributedString` you affected to it, to change its formatting, especially adding itself some bold style to links (note the `copy` attribute in `@property(nonatomic, copy) NSAttributedString* attributedText;` in the header).  
Your original `NSAttributedString` that you created does not have the bold text, but the one copied and displayed by `OHAttributedLabel` has this bold effect added on links because you asked your `OHAttributedLabel` instance to do it with `linkUnderlineStyle = kOHBoldStyleTraitSetBold`. So that's your `OHAttributedLabel` instance that contains the string with the links in bold, not your original `attrStr` instance.

---

To have the size of the `NSAttributedString` after `OHAttributedLabel` has added the formatting you asked (like making links bold), you can't ask your original `attrStr` for its size because it is not formatted with links in bold. **You should instead ask the `OHAttributedLabel` itself for its ideal size, by using its `sizeThatFits:` method.** _This method will in fact call the `sizeConstrainedToSize:` method internally, but on the reformatted attributed string (including some bold or underline style added according to its `linkUnderlineStyle` property)._

**Comment by ghost** [comment]
AliSoftware,

That doesn't seem to work, when I call it like this:

```
CGSize sz = [attStr sizeConstrainedToSize:CGSizeMake(300, MAXFLOAT)];

OHAttributedLabel *contentLbl = [[OHAttributedLabel alloc] initWithFrame:CGRectMake(10, contentIV.frame.size.height + contentIV.frame.origin.x, 300, sz.height)];
[contentLbl setBackgroundColor:[UIColor clearColor]];
[contentLbl setAttributedText:attStr];
[contentLbl setAutomaticallyAddLinksForType:NSTextCheckingTypeLink];
[contentLbl setLinkColor:[UIColor colorWithHexString:@"0x039dd2"]];
[contentLbl setLinkUnderlineStyle:kOHBoldStyleTraitSetBold];
[contentLbl setTag:2];
[__scrollView addSubview:contentLbl];
NSLog(@"Before: %@", contentLbl);
[contentLbl sizeThatFits:CGSizeMake(300, MAXFLOAT)];
NSLog(@"After: %@", contentLbl);
```

Before is: `<OHAttributedLabel: 0xabd7d80; baseClass = UILabel; frame = (10 810; 300 324);`
And after is: `<OHAttributedLabel: 0xabd7d80; baseClass = UILabel; frame = (10 810; 300 324);`

It still jumps out of the screen, or I must not understand sizeThatFits correctly..

Thanks.

**Comment by AliSoftware** [comment]
I don't understand why you expect your NSLog to be different in "Before" and "After"?

`sizeThatFits:` is a standard method (see `UIView` documentation in Apple doc) that _return a `CGSize`_ representing the size you should give the label so it can fit its content. It does not change the label's size. But in your code you don't even use its return value!
You need to retrieve the returned value and use it to adjust the frame yourself.

Maybe you confuse it with the other standard method `sizeToFit` (see in official Apple doc too) that does change the frame directly? Read `UIView` documentation about those two again to better understand the difference.

**Comment by ghost** [comment]
AliSoftware,

I'm sorry I misinterpreted the usage of sizeThatFits, I indeed thought it automatically resized the views like sizeToFit does, very stupid.

Thanks
