### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by vacuumFreedom** [AliSoftware/OHAttributedLabel#115]
Hi,

I get errors (that is: "use of undeclared identifier _linkColor" and and other variables. An image of the error attached) when compiling the OHAttributedLabel.xocdeproject. I am using Xcode version 4.2. 

Is the version of the Xcode the reason of that problem?

Thank you very much,

Jordi
![Captura de pantalla 2013-01-21 a las 16 36 23](https://f.cloud.github.com/assets/3329979/83460/d497cbea-63e0-11e2-9a10-1b5ab00d895c.png)

**Comment by AliSoftware** [comment]
`OHAttributedLabel` does not support Xcode versions as old as version 4.2 (which is now more than 9 versions late), because Xcode 4.2 uses a quite old version of the compiler (llvm-gcc compiler) and an older SDK too.

`OHAttributedLabel` only support the LLVM compiler, especially since the latest versions, which introduced a lot of functionalities like auto-property synthesizes, modern Objective-C and much much more (since Xcode 4.4 especially).
LLVM has been introduced since multiple versions of Xcode now (we have had Xcode 4.3, 4.4, 4.5 and now 4.5.2) and GCC and Xcode 4.2 are now obsoleted even by Apple, and not supported since a while.

You should always use the latest versions of Xcode, because the compiler versions are updated regularly but also because it includes the latest SDK too. Using the latest SDK allows your to make your app run on the latest versions of iOS (but you can still compile for older iOS like iOS5 with SDK 6 too, of course), and submit your application on the AppStore (apps compiled with older versions of the SDK are not validated by Apple).
