### ISSUE TITLE
New warning with XCode 4.6

### ISSUE THREAD

**Issue by clueckler** [AliSoftware/OHAttributedLabel#122]
Hello, 
there occours a new warning with the new XCode 4.6 Compiler: 

"Implicit conversion from enumeration type 'enum NSTextCheckingType' to different enumeration type 'NSTextCheckingTypes' (aka 'enum NSTextCheckingTypes')"

Greez Chris

**Comment by AliSoftware** [comment]
Did you do the integration of `OHAttributedLabel` as explained in the README (especially keeping it in its dedicated xcodeproj, which should avoid your application project's Build/Warning Settings to mess up with `OHAttributedLabel` Build Settings)?

_(Didn't update my Xcode yet, will download the 4.6 update tonight)_

**Comment by clueckler** [comment]
@AliSoftware Hey ... no I have it included for my own and "copied" the build / warning settings
But I don't think that this changes something, because this warning is new (With the new Compiler included in XCode 4.6)

**Comment by AliSoftware** [comment]
Just updated my Xcode to 4.6, but still no new warning here.

I opened my demo project (the one provided in this GitHub repo), cleaned the build folder and even removed the DerivedData folder, performed a build and even an Analyze, but still zero warning.

You should really follow the README instructions for the library integration, that will avoid you a lot of risks like different Build Settings for each projects, settings conflits, could lead on memory leaks (for example if different ARC/non-ARC settings and more), or new warnings like you have, etc.
_(I normally don't provide support for the people who didn't RTFM because that's already a lot of work to make a stable and robust code against all users various configurations and using the integration process recommended by Apple to integrate libraries to workspaces avoids a lot of trouble)_.
