### ISSUE TITLE
Conflicting Parameter Types under Xcode 5

### ISSUE THREAD

**Issue by jdandrea** [AliSoftware/OHAttributedLabel#154]
In Xcode Version 5.0 (5A11386k) I get "Conflicting Parameter Types in implementation of setTextAlignment:" and setLineBreakMode:.

The fix appears to be an easy one though: Change the lone parameter in each method to use NS instead of UI (e.g., NSTextAlignment and NSLineBreakMode, respectively). The underlying values are the same.

Apparently this used to be a warning, and now it's an error. See also:

http://stackoverflow.com/questions/12514421/deprecation-of-the-enum-uitextalignment-in-favor-of-nstextalignment-in-ios6

**Comment by AliSoftware** [comment]
I'll probably use the `#ifdef __IPHONE_OS_VERSION_MAX_ALLOWED` safeguard I already use in the rest of my project, to keep it compatible with older SDKs (especially because `OHAttributedLabel` won't really be maintained much in a near future as `UILabel` now supports `NSAttributedStrings` natively so its sole purpose now is probably for older SDKs)

I thought I removed the warnings with this before, but if you tell me that there are still errors I definitely need to look at it.

**Comment by jdandrea** [comment]
Good move (for older SDK compatibility). As for UILabel supporting NSAttributed strings, point taken!

I only saw that one error as of Xcode 5. Otherwise, you're in good shape!

**Comment by AliSoftware** [comment]
Just pushed a fix for that, on a dedicated branch.
Waiting for my download of Xcode5 GM Seed to finish (I was still at DP2 on my personal mac!! woops) so I can test with the latest Xcode version before merging and releasing a version.

**Comment by AliSoftware** [comment]
version [`3.4.2`](https://github.com/AliSoftware/OHAttributedLabel/releases/tag/3.4.2) tagged and available in [CocoaPods](https://github.com/CocoaPods/Specs/blob/master/OHAttributedLabel).
