### ISSUE TITLE
OHAttributedLabel was rejected as an implicit dependency for 'libOHAttributedLabel.a' because its architectures '' didn't contain all required architectures 'x86_64'

### ISSUE THREAD

**Issue by PGSeattle** [AliSoftware/OHAttributedLabel#165]
This is just a build warning (Resolving target dependencies), but is there any way to fix this?

This warning only appears when selecting the iPhone Retina (4-inch 64-bit) simulator.

**Comment by AliSoftware** [comment]
How do you include `OHAttrbutedLabel` ?
- Using CocoaPods (the most recommended way)? If so, did you upgrade CP to at least 0.25.0, version that supports Xcode5 and the arm64 architecture.
- Adding the xcodeproj as a side project of your own app project in the same workspace (recommended way if you don't use CocoaPods already, even if you should as it makes libraries integration much easier)
- Any other non-recommended way?

If you created your own project, did you try to use "Validate Project Settings" in the Product menu after selecting your various xcodeproj projects in your workspace?

In any case, as with any other static library you include in your project, be sure it is configured to contain all the possible architectures (including arm64 now). "Validate Project Settings" usually fixes that for you (among other things) if not the case already.

**Comment by AliSoftware** [comment]
Hi there,

> In any case, as with any other static library you include in your project, be sure it is configured to contain all the possible architectures (including arm64 now)

Following the information you gave me by email, that was indeed because the "Valid Architectures" settings was not including `arm64`, as I already suggested above. _(It was improperly forced to `i386 armv6 armv7` and I didn't update this since this new architecture was released, my bad)._

Anyway, I fixed it (by simply removing the "Valid Architectures" setting override) in my latest commit e732f6cd6aa20dbd8fcbd38c9de928215d2af6d2 , so you should be good to go now, even when integrating the library manually.

_Note: Of course, anyone using CocoaPods wasn't affected by the issue, as CocoaPods magic already takes care of configuring everything like those settings for us properly._

**Comment by PGSeattle** [comment]
Awesome! Thank you for your help!
