### ISSUE TITLE
Is it possible to assign a attributed string from OHAttributedLabel into UITextview with formatting ?

### ISSUE THREAD

**Issue by sundarsan** [AliSoftware/OHAttributedLabel#185]
Its crashing even on iOS 8.0

**Comment by AliSoftware** [comment]
`OHAttributedLabel` is deprecated and not supported since a while now (and iOS6/7 changed the whole Text Rendering engine). [See README](https://github.com/AliSoftware/OHAttributedLabel/blob/master/README.md) for more details.

Use `UILabel`'s native support for `NSAttributedString` instead, and migrate to `OHAttributedStringAdditions` if you need convenience methods to build your `NSAttributedString` easily
