### ISSUE TITLE
Crash in attributedTextWithLinks when _attributedText is nil

### ISSUE THREAD

**Issue by steveflack** [AliSoftware/OHAttributedLabel#22]
attributedTextWithLinks will throw an exception if _attributedText is nil. Modification of the conditional avoids this

```
-(NSMutableAttributedString *)attributedTextWithLinks {
    NSMutableAttributedString *str = [_attributedText mutableCopy];
        if ((str!=nil) && (self.automaticallyDetectLinks)) {
```

**Comment by AliSoftware** [comment]
Thanks for mentionning this issue.

Anyway, the fix you propose would be a strange fix as this won't avoid the crash later and is not. I prefer checking if `_attributedText` is nil and generate the text in this case... and this is exactly what the property (used as a getter) does.
That's why I just fixed this in my next commit this way.

**Comment by steveflack** [comment]
I don't think using the getter is a fix either. If self.text is nil then the attributedText property is set to nil in -resetAttributedText ... then you're back to having the same problem as originally described.

**Comment by AliSoftware** [comment]
Ok I'll check that case (do you ever had the case when self.text is nil and not @"" ? Oh maybe only if you create your OHAttributedString by code and not from a XIB?)

If [NSMutableAttributedString attributedStringWithString:nil] returns nil and not an empty NSMutableAttString (I am not in front of my Mac right now to test this), then I will just fix it using `self.text?:@""` instead of just `self.text` in `resetAttributedString`.
