### ISSUE TITLE
Using OHAttributedLabel inside a UITableViewCell

### ISSUE THREAD

**Issue by jdandrea** [AliSoftware/OHAttributedLabel#30]
Greetings! Is there anything extra I need to do to use attributed labels inside table view cells?

I'm using black color text with a bold system font for starters. When the cells are displayed, the label text is not visible. If I set the label's background color to something besides white, the label appears as if it's just one pixel tall ... except the frame (92, 20, 187, 64) suggests otherwise!

**Comment by jdandrea** [comment]
Closing issue. Tried using UILabel. Same problem happens, therefore, it has nothing to do with OHAttributedLabel!

**Comment by AliSoftware** [comment]
Maybe your UILabel is in a UIView that is not high enough to display the label itself (as the subviews are clipped by their superview's frame?

**Comment by jdandrea** [comment]
It ended up being pilot error. I was using the wrong protocol method to set up the labels. Moved it and ... ta-dah! (Using Sensible TableView from sensiblecocoa.com.)

**Comment by jdandrea** [comment]
Hello again! Still on topic with using OHAttributedLabel inside a UITableViewCell. Turns out I never noticed that, when I tap the cell, if I happen to tap over the label, it doesn't propagate down to the cell. onlyCatchTouchesOnLinks and automaticallyDetectLinks are both set to NO. hitTest:withEvent:, however, gets a hitResult of self (the label) instead of the table view cell. The label is inside the content view of the cell. Hmm ... I wonder what I'm doing wrong?

**Comment by AliSoftware** [comment]
If `onlyCatchTouchesOnLinks` is set to NO, that's the normal/expected behavior !
- `onlyCatchTouchesOnLinks = YES` means that when your tap on the OHAttributedLabel view, your tap is catched by the label (`hitTest:withEvent:` returns the label) **only** if the tap is on a link.
  _Otherwise, if you tap anywhere else on the label, the tap "pass thru" the label and is not catched by it (`hitTest:withEvent:` returns nil, allowing the view under the label, in your case the cell, to catch the event)_
- `onlyCatchTouchesOnLinks = NO` means the label doesn't only catch touches on links, but **catch touches whereever you tap on the label**. It doesn't test if your tap is on a link or not, it always cat touches.

If you need the label to never catch touches, simply set `userInteractionEnabled = NO`. Or if you don't have any links in your text (`automaticallyDetectLinks = NO`, which must be replaced by `automaticallyAddLinksForType = 0` if you integrate my recent commit), set `onlyCatchTouchesOnLinks = YES` also works (as touches will then only be catched on links, but you don't have any links…)

**Comment by jdandrea** [comment]
I neglected to mention: The very first thing I did was set userInteractionEnabled to NO. Perhaps it is being set to YES outside of the NIB! Will recheck ... (looks at NIB), yep, still NO. Will trace through again and see if there is any other funny business going on.

**Comment by AliSoftware** [comment]
Woops yes it IS forced to YES in the init method of OHAttributedLabel (and thus outside the XIB)… for the opposite reason you have encountered.

In fact, before, when I wasn't altering its value (and kept the one used in the XIB) many users asked me why tapping on a links didn't work and why the link wasn't triggered… and the answer was obviously because they let the default setting of userInteractionEnabled being unchecked in their XIB.
For that reason, I decided to force `userInteractionEnabled` to be set to YES by default, not taking into account the case when it was unchecked in the XIB because as its default value is to be unchecked, many users forgot to check it so that the links in the label can be triggered.

Anyway, if you want the touches not to be captured by the OHAttributedLabel, you only have to set `userInteractionEnabled` to NO in your code… outside of your XIB, after the OHAttributedLabel has been initialized.

**Comment by jdandrea** [comment]
Whew! So I'm not insane. (Well, not completely.) I will force it to NO in code then.
