### ISSUE TITLE
Vertically centering OHAttributedLabel objects

### ISSUE THREAD

**Issue by jdandrea** [AliSoftware/OHAttributedLabel#31]
Is there a built-in way to gracefully vertically center OHAttributedLabel objects?

If not, perhaps something like this could be incorporated ... ?

https://discussions.apple.com/message/10270072?messageID=10270072#10270072

**Comment by AliSoftware** [comment]
Doesn't the `@property(nonatomic, assign) BOOL centerVertically;` property in OHAttributedLabel.h fit your needs already?!

**Comment by jdandrea** [comment]
D'oh! How embarrassing. I totally missed that. TWICE. :(

**Comment by AliSoftware** [comment]
To be more precise, the suggested solution works only for UIKit but is a bit more complex with CoreText (that OHAttributedLabel uses as it is the only way to draw NSAttributedStrings) because CoreText has to compute framing (according to attributes of each text run with different styling attributes and so on) ;-)

**Comment by jdandrea** [comment]
Understood. Not as cut and dry. Also, YES, that does work. Profuse apologies for not catching that - it was right in front of my face! Let's hear it for developer myopia. :)

**Comment by AliSoftware** [comment]
No problem ;-)
