### ISSUE TITLE
Using OHAttributedLabel in custom cell disturbing other code

### ISSUE THREAD

**Issue by saimayaqub** [AliSoftware/OHAttributedLabel#35]
Hello,

I am trying to use OHAttributedLabel in my custom cell. It works great as for as Attributed string part is concerned. But at the same time, it disturbs my previous functionality. Let me explain my issue... 

I defined some code in my didSelectRowAtIndexPath class, which navigates to the view having details of the selected table cell (on clicking/tapping the cell contents). This code worked fine before I started using OHAttributedLabel. But now every time I click the cell contents, it only makes the cell contents bolder instead of navigating to next view. 
I am stuck on the issue. Please let me know how to modify the classes such that it should still fire didSelectRowAtIndexPath method the way it did prevoiusly.

Any help is highly appreciated.
Thanks

Salman

**Comment by AliSoftware** [comment]
That's where `onlyCatchTouchesOnLinks` takes place: set this property to YES so that the OHAttributedLabel only capture the UITouches on the links you may have in your OHAttributedLabel's text, but "pass thru" (to the cell) if the tap is on "standard (untappable) text (i.e. not a link).

If you keep `onlyCatchTouchesOnLinks` to NO, the OHAttributedLabel will capture the touches whereever they occur on the OHAttributedLabel (on a link or not on a link), thus the cell underneath won't get the UITouchEvent.

If you set `userInteractionEnabled` to NO,  OHAttributedLabel won't capture **any** touch event, even if the UITouch occurs on a link of the AttributedLabel (warning: `userInteractionEnabled` is forced to YES in the init method of OHAttributedLabel, as a lots of users forgot to toggle it to YES in InterfaceBuilder and wondered why tapping on a link wasn't working then... So if you want to force it to NO, you should do it by code after the init, and not in IB)

Anyway, setting `onlyCatchTouchesOnLinks` to YES seems a better compromise, allowing the user to tap on a link in the attributedLabel if there is one, and tapping on the cell underneath otherwise.

(I will probably defaults this property to YES instead of NO in a future commit?)

**Comment by saimayaqub** [comment]
Thank you very much for your prompt reply.
It works really great. This is what I was looking for.

Thanks again
Salman
