### ISSUE TITLE
enumerator block changing textLinks

### ISSUE THREAD

**Issue by RickiG** [AliSoftware/OHAttributedLabel#39]
I am implementing a custom UITableViewCell and it has an updateCell method that is called from cellForRowAtIndexPath.

In -(NSMutableAttributedString*)attributedTextWithLinks there is an enumerator block that loops the custom links and sets the color and underline. It seems that when drawRect is called on the cell this blocks runs.

I now experience that the my app crashes as I scroll, I think it is due to the block changing the text attributes for cells that are off screen and as it returns and finds the cell has changes. It will choke on the Range for setTextColor being the Range from a previous cell. I am having a hard time debugging it as blocks don't disclose who "owns" them.

**Comment by AliSoftware** [comment]
Hi

I use OHAttributedLabel with custom links all the time in my app without any problem myself. The enumeration block for finding custom links is the standard enumeration block of the iOS SDK, which is synchronous (this enumeration is not executed on a separate thread, even if it is a block it is not related to GCD or whatever here)

Anyway something is shocking me when I read your post : you call an "updateCell" method… from cellForRowAtIndexPath ? Hope you don't do any drawing there nor complex code as these methods needs to be designed to be fast and for layout only, not for complex computations (that must be done before the reloadData mechanism, is the scrolling of your tableview needs to be fast and fluid)

`attributedTextWIthLinks` is called only in drawRect — which is called by iOS during the drawing loop — and if you call `sizeToFit` or `sizeThatFits` (so compute the size of the OHAttributedLabel to adjust it depending on its content, so this should not be called at all in `cellForRowAtIndexPath`, except if you resize the frame of the label using `sizeToFit` instead of using an AutoresizingMask (as the `sizeThatFits` or equivalent should only be useful in `heightForRowAtIndexPath` in this case, not `cellForRowAtIndexPath`… so anyway I don't see the logic of your code here ?!

Be sure to respect the basic rules of both TableView programming guide and the base of drawing mechanism of iOS — especially for example only performing drawing operations in the `drawRect` method, and only on the main thread of your app. And of course, respecting the standard layout of the `cellForRowAtIndexPath` method (using the "reuse" mechanism with its reuseIdentifier, only initializing common features when the cell is created and not reused, only change the properties that are different from one cell to another outside the "if" … ) as described in the Programming Guide in apple doc.

_PS : If there is still a problem in your code, can you provide more info ? Giving what you said in your original message isn't enough to help you debug anything (what is the error or exception message or signal, what does the carshlog says, what is your code in your `cellForRowAtIndexPath`, …_

**Comment by RickiG** [comment]
Hi
I mailed you a simple test project with just a tableView and a OHAttributedLabel.

```
// Customize the appearance of table view cells.
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    static NSString *CellIdentifier = @"Cell";

    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];
    if (cell == nil) {
        cell = [[[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:CellIdentifier] autorelease];

        OHAttributedLabel *label = [[[OHAttributedLabel alloc] initWithFrame:CGRectMake(15.0f, 15.0f, 250.0f, 20.0f)] autorelease];
        [label setFont:[UIFont systemFontOfSize:12.0f]];
        [label setTextColor:[UIColor darkGrayColor]];
        [label setBackgroundColor:[UIColor clearColor]];
        [label setTag:1337];
        [label setDelegate:self];
        [cell.contentView addSubview:label];
    }

    NSString *baseString = [self.wordList objectAtIndex:indexPath.row];    
    NSMutableAttributedString *attributedString = [NSMutableAttributedString attributedStringWithString:baseString];

    [(OHAttributedLabel*)[cell viewWithTag:1337] setAttributedText:attributedString];
    NSString *urlString = [NSString stringWithFormat:@"user://%@", baseString];
    [(OHAttributedLabel*)[cell viewWithTag:1337] addCustomLink:[NSURL URLWithString:urlString] inRange:[baseString rangeOfString:baseString]];

    // Configure the cell.
    return cell;
```

}

This crashes at (NSRangeException)
    [self removeAttribute:(NSString \* )kCTForegroundColorAttributeName range:range]; // Work around for Apple leak

Due to using a previous range to update the new string.

Is there anything wrong with the above?

**Comment by AliSoftware** [comment]
Hi Ricky

Received your email but won't have time to check on that before this weekend.
Will check that ASAP and be back to you probably on saturday or sunday.

**Comment by RickiG** [comment]
Thanks Oliver
I got some help from Ullrich, the custom links needs to be removed on each update.
https://gist.github.com/1186172

**Comment by AliSoftware** [comment]
Great !

I added a comment on the gist you mentionned: actually I did a correction locally on my Mac quickly this morning and planned to commit it ASAP... and this would solve your issue too!

Actually for my case, I only encounter cases when I change the text to a **longer** string, and the customLink ranges were conserved. So even if it didn't crash like in your case (because ranges were still valid), they were still there whereas it is a nonsense to keep them (with the ranges provided before) if the text is changed.

So even if I didn't crash like in your case, the origin of the issue were the same as yours, and my comming commit/push (probably tonite) should solve this too :)

**Comment by AliSoftware** [comment]
Hi @RickiG

Just commited some corrections that do fix this issue (I tested it myself with the sample project you sent me by mail, after replacing OHAttributedLabel files with the new one just commited the app does not crash)

Thanks again for the reporting and investigation!

**Comment by RickiG** [comment]
Hi @AliSoftware

Great! Thanks. I'll remove the workaround I did and pull the update.
