### ISSUE TITLE
Label must have minimum height of 18?

### ISSUE THREAD

**Issue by FunkeeMonk** [AliSoftware/OHAttributedLabel#42]
First of all, thanks for open-sourcing this project!  It's been a big timesaver.

In the project i'm working on now, it seems that if an OHAttributedLabel has a height <= 17, the label's text won't show up.  I haven't been able to replicate this in the demo project yet though.

Any hint on why this may be happening?

**Comment by AliSoftware** [comment]
Yes.

Contrary to UIKit, when CoreText layout the lines of text to draw them in a view (using a CTFrameSetter), it stops the framing process if a line wan't fit in the frame of the destination view.

This means that if you have a view 35 pixels high and you try to render some text in a font that has a line height of 18 (which will probably correspond to a font size of sthg like 14 or 15, as line height = font size + ascent + descent + linespacing), then it will render the first line in the 18 upper pixels, but will not have enough room to draw the whole 18 pixels of the second line in the 17 pixels remaining at the bottom... so it won't even render part of it like UIKit does but instead it will not generate (nor render) this second line at all.

This is a bit annoying but that's how CTFrameSetter works.

To workaround this without changing the code, you can either increase the height of the OHAttribtedLabel so that the last line will fit (or use `sizeToFit` or `sizeThatFits:` methods to resize the label to fit the needed height)

A workaround in OHAttributedLabel would be to do the framing process ourselves line by line (managing word wrapping, etc) so that we can do our own framing and render the last CTLine even if it is partially visible, instead of using CTFrameSetter that does this automatically so far.
