### ISSUE TITLE
sizeToFit no longer works

### ISSUE THREAD

**Issue by bdittmer** [AliSoftware/OHAttributedLabel#47]
It appears that changes to sizeThatFits have broken sizeToFit. Unclear if this was intentional or not. Reverting to the old version, below, fixes the issue.

``` objective-c
- (CGSize)sizeThatFits:(CGSize)size {
    NSMutableAttributedString* attrStrWithLinks = [self attributedTextWithLinks];
    if (!attrStrWithLinks) return CGSizeZero;

    CTFramesetterRef framesetter = CTFramesetterCreateWithAttributedString((CFAttributedStringRef)attrStrWithLinks);
    CGFloat w = size.width;
    CGSize sz = CTFramesetterSuggestFrameSizeWithConstraints(framesetter,CFRangeMake(0,0),NULL,CGSizeMake(w,CGFLOAT_MAX),NULL);
    if (framesetter) CFRelease(framesetter);
    return CGSizeMake(sz.width,sz.height+1); // take 1pt of margin for security
}
```

**Comment by AliSoftware** [comment]
Actually the former code (that you quoted above) was not compliant with the sizeThatFits standard behavior, because it ignored the height value of the `size` parameter.
- `sizeThatFits:` takes a size as a parameter, and should return the size that **fits** in this given size, making sure it won't be bigger than this size
- The default implementation of `sizeToFit` (not to be mistaken with `sizeThatFits:`) calls the `sizeThatFits:` method, passing the superview' size as its parameter, so that the label fits in its superview.

So the former implementation of `sizeThatFits:` that you quoted above was _not_ taking the height of the passed CGSize parameter into account, and that was a wrong behavior/implementation. Thus the correction, that did not break `sizeThatFits:` but rather fixed it to its normal behavior according to Apple's documentation.

---

### Note that you should use it this way (as for any UIView, by the way) :
- If you want your OHAttributedLabel to expand its size so it takes all the space given by its superview, add the OHAttributedLabel to its superview first, sizing its superview according to the maximum space you want to give, and only then call `sizeToFit`. This is what Apple's UIView documentation explains.
- If you want to resize your OHAttributedLabel so that it makes all its text visible, simply call `sizeThatFilts` with the appropriate parameters (depending on the maximum width and height you allow your OHAttributedLabel to take) to retrieve a `CGSize`, and appy this returned `CGSize` to the bounds of your `OHAttributedLabel` yourself.

For the latter case, you can pass whatever you need as a `CGSize` parameter. For example :
- `CGSizeMake([[UIScreen mainScreen].bounds.size.width, CGFLOAT_MAX)` if your OHAttributedLabel can take no more than the whole screen width, but unlimited in height
- `CGSizeMake(CGFLOAT_MAX, 50)` if it can take all the width it needs (even if it makes it larger than the screen, which can still makes sense for example if you put it inside a `UIScrollView`) but be restrained by 50 points in height
-  superview.bounds.size`if… you want to mimics the behavior of`sizeToFit`
- and so on, depending on your needs
