### ISSUE TITLE
adjustsFontSizeToFitWidth not working?

### ISSUE THREAD

**Issue by menetwork-erik** [AliSoftware/OHAttributedLabel#49]
Why is it that the adjustsFontSizeToFitWidth is not working?

OHAttributedLabel *lbl = [[[OHAttributedLabel alloc] initWithFrame:aCGRect] autorelease];
lbl.numberOfLines = 1;
lbl.backgroundColor = [UIColor clearColor];
lbl.adjustsFontSizeToFitWidth = YES;
lbl.text = strVar;

NSMutableAttributedString\* attrStr = [lbl.attributedText mutableCopy];
[attrStr setTextColor:phone.textColor];
[attrStr setFont:aFont];
[attrStr addAttribute:(NSString*)kCTUnderlineStyleAttributeName value:[NSNumber numberWithInt:kCTUnderlineStyleSingle|kCTUnderlinePatternSolid] range:[name.text rangeOfString:name.text]];
lbl.attributedText = attrStr;
[attrStr release];

[cell addSubview:lbl];

**Comment by AliSoftware** [comment]
Because CoreText can't manage such behavior (contrary to UILabel's AppKit drawing system).

And I don't plan to support this : Quite complicated to implement the laying out of a complex NSAttributedString and changing the size of the different parts of the NSAttributedString (which can be composed of a lot of different CTFont sizes) to handle this : this is really complex both to implement (contrary to what AppKit does with an ordinary NSString which is only composed of a single NSFont) and long to compute (it would dramatically reduce the performance, which will especially make it impossible to use in a context of scrolling views like UITableViews.

Anyway, feel free to fork and implement it yourself if you want :) As long as it won't break integrity and keep good drawing and layout computation performance good, if you propose a fix for that I would pull your code into the repo

**Comment by AliSoftware** [comment]
Note: added warning about such unsupported features in the latest commit
