### ISSUE TITLE
Memory leak in setFontName

### ISSUE THREAD

**Issue by noahmiller** [AliSoftware/OHAttributedLabel#5]
Instruments' memory leak detector shows some leaks in the sample project, seemingly from 
    setFontName:(NSString*)fontName size:(CGFloat)size range:(NSRange)range
when multiple fonts are set for the same attributed string.

I think those leaks are inherent to the NSAttributedString+Attributes category, as they appear in my project as well.  In the example project, I have to click the '"World" in bold, 24' button a few times.

I also see leaks in drawTextInRect: and setTextAlignment.

**Comment by AliSoftware** [comment]
Hi Noah,

Thanks for your message.
You're right I also see leaks in Instruments in the same methods in `NSAttributedString+Attributes`.
Anyway, I don't see what's wrong in my memory managment, do you have any clue?

For example, in `setFontName:(NSString*)fontName size:(CGFloat)size range:(NSRange)range`, the call to `CTFontRef aFont = CTFontCreateWithName(...)` is balanced with `CFRelease(aFont)` so I don't get why there is a leak there.

Any idea what I am doing wrong?

**Comment by noahmiller** [comment]
You're right, the code looks fine, and I wasn't sure what was causing the memory leak.  I stepped through the code for displaying one attributed string with Helvetica and HelveticaBold, and one time out of around 8 calls HelveticaBold was returned with a retainCount of 2.  So maybe there's a memory leak in the underlying code, or maybe there's some subtle call pattern that the code expects.  Sorry I can't be more help!

**Comment by AliSoftware** [comment]
Ok, that's a bit reassuring I'm doing the thinks right concerning Mem Mgmt, but that does not solves this leak.

I vote for a leak in the underlying Apple's code as if your calls to HelveticaBold returns with a retainCount of 2, this does not seems logical.
Maybe some particularities with the way Apple is managing the underlying CTFonts that they reuses each time instead of recreating them from scratch? Seams strange anyway. (maybe we should open a radar bugreport about that)

Thanks for your investigation!

**Comment by hollance** [comment]
I'm seeing the same leaks but your code looks OK.

**Comment by AliSoftware** [comment]
Thanks Matthijs.

Guess I will file a bugreport to Apple then.

**Comment by AliSoftware** [comment]
Noah when you say that you observed a leak about 1 times out of 8, are you sure it is because it really happen 1 times out of 8, or isn't it because Instruments only check for leaks every 10 seconds (and does not report leaks in between until the next 10 seconds cycle or if you ask Instruments to check it manually using the button on the left panel) ?

**Comment by steveflack** [comment]
We've seen this in our testing using OHAttributedString. It's also reported in this posting here:

http://osdir.com/ml/coretext-dev/2010-12/msg00021.html

There seem a number of ways around this. One is mentioned in the post above - add the attribute as a dictionary. The other we have used is to remove the existing attribute before adding it - for example in OHCommodityStyleModifiers - this is mentioned later in the thread.

-(void)setFontName:(NSString \* )fontName size:(CGFloat)size range:(NSRange)range {
        // kCTFontAttributeName
        CTFontRef aFont = CTFontCreateWithName((CFStringRef)fontName, size, NULL);
        if (!aFont) return;
        [self removeAttribute:(NSString \* )kCTFontAttributeName range:range];                // Work around Apple leak.
        [self addAttribute:(NSString \* )kCTFontAttributeName value:(id)aFont range:range];
        CFRelease(aFont);
}

There several places where the attributes are set in that category and, although we've only seen it leak for fonts, it might be prudent to do something similar for all the addAttribute:value:range: calls.

**Comment by AliSoftware** [comment]
Thanks, the hack/fix for this Apple leak has been applied, it should be ok now :)

**Comment by NaveenShan** [comment]
I also have  same memory issue. how can I fix it. the memory is keep growing. I use a big string

**Comment by AliSoftware** [comment]
Just update (pull). I fixed this issue one month ago.

**Comment by alexissan** [comment]
hi!,
I've been using OHAttributedLabel in iOS 5.0 and 5.1 with xcode 4.4.1 and i get this error in console:

Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds'

the error is in:

-(void)setFontName:(NSString*)fontName size:(CGFloat)size range:(NSRange)range
{
    // kCTFontAttributeName
    CTFontRef aFont = CTFontCreateWithName((BRIDGE_CAST CFStringRef)fontName, size, NULL);
    if (aFont)
    {

//THE ERROR IS IN THIS LINE

```
    [self removeAttribute:(BRIDGE_CAST NSString*)kCTFontAttributeName range:range]; // Work around for Apple leak
    [self addAttribute:(BRIDGE_CAST NSString*)kCTFontAttributeName value:(BRIDGE_CAST id)aFont range:range];
    CFRelease(aFont);
}
```

}

sorry by my english, i'm spanish ;)

**Comment by AliSoftware** [comment]
Hi @alexissan 
- I don't understand why you post this in an issue related to a memory leak whereas your issue is clearly an NSRangeException, not a memory leak, so that's a totally different problem
- Did you at least use a valid `range` parameter when you called the `setFontName:size:range:` method? When the exception occured, who was the called and which `range` did it pass as a parameter? Of course if you pass a `range` that is invalid or out of the bounds of the string, the exception is totally normal and logical.
