### ISSUE TITLE
One-line text disappears inside UITableView

### ISSUE THREAD

**Issue by a-chernykh** [AliSoftware/OHAttributedLabel#51]
Hello,

My app is using OHAttributedLabel in UITableView. I am loading my cell from XIB which has OHAttributedLabel.

``` objective-c
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *CellIdentifier = @"ImageCommentCell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];
    OHAttributedLabel *commentLabel;
    CGRect labelFrame;

    if (cell == nil) {
        [[NSBundle mainBundle] loadNibNamed:@"ImageCommentCell" owner:self options:nil];
        cell = _imageCommentCell;
        _imageCommentCell = nil;
    }

    commentLabel = (OHAttributedLabel *)[cell viewWithTag:2];
    labelFrame = commentLabel.frame;
    labelFrame.size.height = 18;
    commentLabel.frame = labelFrame;
    commentLabel.attributedText = [NSAttributedString attributedStringWithString:@"test"];
    [commentLabel setNeedsDisplay];

    return cell;
}
```

My table loads fine initially (with "test" text in each cell). But when I scroll up and down the "test" text suddenly disappears in some cells. If I comment out the following code then everything works fine:

``` objective-c
labelFrame = commentLabel.frame;
labelFrame.size.height = 18;
commentLabel.frame = labelFrame;
```

But I still need a way to setup the height dynamically for each label (depending on the size of text).

Thanks,
Andrey

**Comment by AliSoftware** [comment]
CoreText rendering does not use the same metrics as UIKit. A UIFont with a size of 18pt will not necessary use exactly 18pt in CoreText. _(And the problem with CTFrameSetter is that even if even half a pixel is missing -- it uses subpixelling -- for the text line to be drawn entirely, it does not layout this CTLine instead of drawing it partially. This is already explained in other closed issues)_

**The right way to get the dimentions of an `NSAttributedString` drawn using CoreText is to use the methods I provide in `NSAttributedString+Attributes.h` like `-(CGSize)sizeConstrainedToSize:(CGSize)maxSize;`**

You can also use the standard `sizeToFit` or `sizeThatFits:` methods on the `OHAttributedLabel` -- as you would do on any other `UIView` -- as I implemented those standard methods in `OHAttributedLabel` (which calls the `sizeConstrainedToSize:` on the underlying `NSAttributedString` for you get the dimensions and size the label accordingly)

**Comment by a-chernykh** [comment]
I've tried to use sizeConstrainedToSize:

``` c
NSAttributedString *str = [NSAttributedString attributedStringWithString:@"test"];
commentLabel = (OHAttributedLabel *)[cell viewWithTag:2];
labelFrame = commentLabel.frame;
CGSize siz = [str sizeConstrainedToSize:CGSizeMake(320, 20)];
labelFrame.size = siz;
commentLabel.frame = labelFrame;
commentLabel.attributedText = str;
[commentLabel setNeedsDisplay];
```

And sizeToFit:

``` c
NSAttributedString *str = [NSAttributedString attributedStringWithString:@"test"];
commentLabel = (OHAttributedLabel *)[cell viewWithTag:2];
commentLabel.attributedText = str;
[commentLabel sizeToFit];
[commentLabel setNeedsDisplay];
```

However, my text is still hidden after scroll.

Andrey.

**Comment by AliSoftware** [comment]
I doublt that your `commentLabel` is 320 points wide when displayed in your tableview (given the margins inside the tableview cells -- especially if your TableView is using the Grouped style), you should use the real value used after the cell has been laid out by the tableview on the screen.

Same for your call to `sizeToFit` which will compute the size before the cell may have its frame changed by the tableView (check also the `autoresizingMasks` you use, I you have some they probably change the frame dynamically when the cell is resized by the tableView upon display)

To fix this, you need to determine the width of the label once the cell has been reframed by the tableview, and also make sure you don't have any autoresizingMask that may change the `OHAttributedLabel` frame when the cell has its frame changed as you manage the `OHAttributedLabel` frame manually.

Just to be sure that this issue is really related to sizing issues that make the text not being laid out by the CTFrameSetter, what if you try to add some security margins in your initial code (forcing the height of the OHAttributedLabel to say 22 instead of 18) ? Even if it's not a real solution this would confirm (or not) the source of the problem before investigating further.

**Comment by a-chernykh** [comment]
Setting label's <code>autoresizingMask</code> to <code>UIViewAutoresizingNone</code> does the trick.

Thanks for your help and sorry for bothering.
