### ISSUE TITLE
ohattributedlabel changes position?

### ISSUE THREAD

**Issue by VeeruPV** [AliSoftware/OHAttributedLabel#59]
Hi there, 
First of all, thanks for the time saving component. It works wonderfully, except for something that i have noticed.

For example I have set a ohattributedlabel, with a frame let's say - 0,20,320,50 - i wanted it on top and i have status bar visible. So the "20" should accommodate for the top status bar.
On the first look it is absolutely as expected, displays fine.
But when change to a different tab and come back the label moves lower, may be - 0,40,320,50 - and i have no idea why. Am not doing an re-drawing or anything.

The creation of the label is inside viewDidLoad method.

How can i fix this? Is there something that i am missing?

Thanks
Veeru

**Comment by VeeruPV** [comment]
I have tried without a status bar in my app and it seems to behave well, is it something to do with the status bar?

**Comment by AliSoftware** [comment]
It does not seem to be related to `OHAttributedLabel` at all.

It is very probably related to the fact that the view of your `UIViewController` is adjusting to fit the status bar.
_I bet that if you use a simple `UILabel` instead of a `OHAttributedLabel` you will have the exact same issue._

You should adjust the frame of your UIView component (in this case `OHAttributedLabel`) in the `viewDidAppear` to fix this, as at this time the status bar is taken into account and the frame of view of your `UIViewController` has been adjusted by the system automatically.

**Comment by VeeruPV** [comment]
I understand what you meant, i shall try it out and post the result here - i believe you are correct. Thanks

**Comment by VeeruPV** [comment]
Yeah, it seems to be nothing to do with OHAttributedLabel. 
My scenario is, initially the app does not have a status bar (During the opening animation) and show up the status bar after that. But the label is created even before statusbar is set to visible. I have worked around the logic of the startup animation and things seem to be fine.

Thanks and sorry for opening an issue on this one :)
