### ISSUE TITLE
sizeThatFits/sizeToFit does not return the correct width (with fix)

### ISSUE THREAD

**Issue by jasonboyle** [AliSoftware/OHAttributedLabel#6]
The sizeThatFits: method of OHAttributedLabel currently returns the with of the size argument that it is passed rather than the width of the string.

``` objective-c
- (CGSize)sizeThatFits:(CGSize)size {
    NSMutableAttributedString* attrStrWithLinks = [self attributedTextWithLinks];
    CTFramesetterRef framesetter = CTFramesetterCreateWithAttributedString((CFAttributedStringRef)attrStrWithLinks);
    CGFloat w = size.width;
    CGSize sz = CTFramesetterSuggestFrameSizeWithConstraints(framesetter,CFRangeMake(0,0),NULL,CGSizeMake(w,CGFLOAT_MAX),NULL);
    if (framesetter) CFRelease(framesetter);
    return CGSizeMake(w,sz.height+1); // take 1pt of margin
}
```

This can be easily fixed as follows:

``` objective-c
- (CGSize)sizeThatFits:(CGSize)size {
    NSMutableAttributedString* attrStrWithLinks = [self attributedTextWithLinks];
    CTFramesetterRef framesetter = CTFramesetterCreateWithAttributedString((CFAttributedStringRef)attrStrWithLinks);
    CGSize sz = CTFramesetterSuggestFrameSizeWithConstraints(framesetter,CFRangeMake(0,0),NULL,CGSizeMake(size.width,CGFLOAT_MAX),NULL);
    if (framesetter) CFRelease(framesetter);
    return CGSizeMake(sz.width,sz.height+1); // take 1pt of margin
}
```

**Comment by AliSoftware** [comment]
Hi

Thanks for your feedback.

Actually as some would say, "this is not a bug, but a feature" ;-)
This is mode a choice of conception actually : I choose to have a fixed width because in all the projects I used my OHAttributedLabel class, I called sizeToFit to adjust the height of the label depending on the number of lines and so on.

For example, having a label 200px-wide, writing some text in it and then calling sizeToFit will resize it to, let's say, 195px.
Then changing the text to something else would layout this text in a label 195px wide, thus maybe making some words going to the next line and needing the label to be one more line high.

In fact the solution you propose is quite the good one, as one expect sizeToFit to resize the label to the smallest size possible that make the text fit, but in practical situations, it is more useful (at least for me) to keep its width constant and only adjust its height. It would be quite painful to store the width in a variable, call sizeToFit, then restore the stored width so that there would not be any side effects to the text rendering.
A good compromise would be to declare a method called "sizeToFitHeight" that calls sizeThatFits, and resize the label using only the height of the CGSize returned, ignoring the width (that it will keep constant), and keep the standard "sizeToFit" method reducing the width of the label. That should do the trick and keep the possibility to have both behaviors and still being able to avoid the side-effect I had in my application when changing the text dynamically. I may implement the both solutions in a near future.

Thanks again

**Comment by AliSoftware** [comment]
Hi @jasonboyle,

Just to let you know that I just pushed a commit on github with your fix for sizeThatFits.

(and I finally adapted my own code to only use the height of this returned size, ignoring the width, when I want my labl to keep a constant width and only adjust its height to fit its content)

Thx

**Comment by jasonboyle** [comment]
Thanks!  I'm glad you found my input helpful.
