### ISSUE TITLE
Is OHAttributedLabel supports copy,paste features?

### ISSUE THREAD

**Issue by karthikeyanvijayan** [AliSoftware/OHAttributedLabel#61]
HIi

Thanks for this awesome lib , i want to know that it support copying the text and all ops like cut,copy paste etc.

**Comment by AliSoftware** [comment]
Hi @karthikeyanvijayan 

At that time the copy/paste feature is not yet supported, as CoreText does not support it natively.
For this to be supported, it will need the feature to be implemented manually (managing and highlighting the selection in an NSAttributedString being the most complex, especially with mixed fonts & style).

**Comment by AliSoftware** [comment]
Note that on the other way, if this workaround fits your needs, you may add a button or a UIGestureRecognizer or thg that copy the text to the NSPasteboard

**Comment by karthikeyanvijayan** [comment]
Thank you so much and will make a try if possible

**Comment by RATTLESNAKE-VIPER** [comment]
Hi @karthikeyanvijayan 

I have made CopyableAttributedLabel by forking an excellent library OHAttributedLabel contributed by AliSoftware which supports copy-paste features; providing a way to highlight the selection in an NSAttributedString and copy it to UIPasteboard.

You can have a look at: https://github.com/RATTLESNAKE-VIPER/OHAttributedLabel.git

Hope this helps.
Thanks

**Comment by kong707** [comment]
How about if we want to use "Speak" behavior that is built-in  in iOS6 ?  How to make text in OHAttributedLabel speakable ?

**Comment by RATTLESNAKE-VIPER** [comment]
@kong707 You can use "Accessibility and VoiceOver” feature in order to make user interface elements to VoiceOver users. But regarding selection of a word based on the VoiceOver is little tricker unlike in webview/safari which automatically shows the "speak" action and makes the selection as well.

UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, @"Your text");

You can override setText method of a label,
- (void) setText:(NSString *)text {
  // Set the text by calling the base class method.
  [super setText:text];
  // Announce the new text.
  UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, text);
  }
