### ISSUE TITLE
NSInvalidArgumentException for NSMutableAttributedString 

### ISSUE THREAD

**Issue by tarekjradi** [AliSoftware/OHAttributedLabel#69]
I was using the same example in my project using ARC, "I revised all codes review according with inssue #48 " 

but when i use in my viewDidLoad:
# define TXT_BEGIN "Discover "
# define ...
- (void)viewDidLoad
  {  
  NSString\* txt = @ TXT_BEGIN TXT_BOLD TXT_MIDDLE TXT_LINK TXT_END; 
  
  NSMutableAttributedString\* attrStr = [NSMutableAttributedString attributedStringWithString:txt];
  ...

occurred the error

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSAttributedString attributedStringWithString:]: unrecognized selector sent to class 0x1659590'

**Comment by Matata-lol** [comment]
you can add "-fno-objc-arc" flag to the files of OHAttributedLabel folder in Build Phases-> Compile Sources

**Comment by AllenWang** [comment]
Wrong answer may break someone's heart. The solution I found to resolve this problem is that add "-ObjC" flag to your project->your target(caution!)->other link flags

**Comment by AliSoftware** [comment]
The flag is normally already present in the latest versions of `OHAttributedLabel` (3.1.0) isn't it?
(Will ensure to check that when back at home anyway)

**Comment by AllenWang** [comment]
There is nothing wrong with your project. 
This flag must be added in user's project.
Check this : http://stackoverflow.com/questions/861626/how-to-resolve-unrecognized-selector-sent-to-instance
"Set flag -ObjC in Other linker Flag in your Project setting... (Not in the static library project but the project you that is using static library...) And make sure that in Project setting Configuration is set to All Configuration."

This problem caused by use extension in imported project.

Finally, sorry for my terrible english. :(

**Comment by AliSoftware** [comment]
Ok yes I do know this `-ObjC` flag must be added in the user's project. And **that's exactly why I explained it in my README file** and in the dedicated page on my Wiki! (People should read the README files before filing issues…)

But thanks for pointing out to the OP that the lack of this `-ObjC` flag in his own project was the real reason of his crash ;)
