### ISSUE TITLE
Reduce memory usage of OHAttributedLabel and drawTextInRect

### ISSUE THREAD

**Issue by lloydsheng** [AliSoftware/OHAttributedLabel#82]
I am using OHAttributedLabel in my project, about 24 OHAttributedLabel used 1.02M memory,  i found the memory used by - (void)drawTextInRect:(CGRect)aRect, could us reduce this memory consumption?

**Comment by AliSoftware** [comment]
Assuming the memory is used because of the use of the CoreText framework, I am not sure if that can be reduced a lot... I'll check that ASAP anyway.

**Comment by AliSoftware** [comment]
The only two stuff that shows some memory peak in Instruments are :
- the `CTFrameSetterCreateWithAttributedString` and `CTFrameSetterCreateFrame` CoreText functions, that can't be avoided as CoreText needs it to lay out the text, and I don't have control over this Apple function internal optimization possibilities. And In fact **this part has already been optimized**, as the framesetter is only created when the `CTTextFrame` has been invalidated and needs to be recalculated, but the `CTTextFrame` is cached by my code so I already reduced the amount of time this function is called and allocation is needed.
- the `reomputeLinksInTextIfNeeded` but this one too has **already been optimized** as the code is only called when needed, and the `NSDataDetector` used enumerate matches (by calling the `DDScannerScanStringWithRange` function that creates the memory peak) only when the text is changed, and caches the result too to avoid recomputing it each time the `drawTextInRect` method is called. The creation of the `NSDataDetector` itself is cached too (as it takes time to create one and may crash at runtime when stress-allocated, according to a previous issue on this github)

So everything is already optimized at its best as those two functions are CoreText and DDDataDetector library functions (provided by Apple) that I can't optimize by myself, and the results of these methods are already cached by `OHAttributedLabel` to avoid computing them again when possible, reducing the memory footprint and optimizing the timing here too. _(Besides if you look into instruments, these allocations are quite small compared to the rest of the allocations)_. I really can't do more to reduce it anymore (but you can issue a radar to Apple about the ones created by CoreText and DDDataDetector libraries I use).

**Comment by nicolamontini** [comment]
Unfortunately there is another memory problem: inside drawTextInRect another function uses a lot of memory, and the function is CTFrameDraw(), as you can see from the following two screenshots:

![screenshot1](https://f.cloud.github.com/assets/2242267/541734/7bc68546-c214-11e2-91d0-dd10d86baa85.png)
![screenshot2](https://f.cloud.github.com/assets/2242267/541737/84c5d4a8-c214-11e2-9b24-f6e69408547a.png)

In the first one you can see that the heaviest elements tracked by Instrument's heapshot are related to OHAttributedLabel (several ones make the heap grow 1,50 KB and some other ones make the heap grow 1,00 KB, I got to know this by inspection); in the second screenshot you can see the particular instruction that is retaining memory for each of the elements listed in the first screenshot. I cannot figure out how to free up that memory

**Comment by coppercash** [comment]
Not just OHAttributedLabel, I find even UILabel use a lot of memory in drawTextInRect: . 
Thus (UITableView) + (UILabel) = (a lot of memory can't be released) .T-T

**Comment by nicolamontini** [comment]
That's right. The memory problem was a fault of mine. Thanks anyway.

**Comment by coppercash** [comment]
It sounds like you already have a solution. 
Can you tell me about it? 
My app's memory using is still increasing because of the UITableView and UILabel combination.

**Comment by nicolamontini** [comment]
In my situation the problem is hidden by the lots of objects I see in the heapshots. It has really nothing in common with OHAttributedLabel, UILabel or UITableView. The majority of the objects you see in my heapshot are not the cause of the memory, but a simple consequence of another problem: in my scenarios, usually the main problem is a controller that is still referenced, but no longer required. In this case, if you (as a user, not as a code writer) enter and exit from the controller, there will be each time a new instance of the controller, and each instance will create many copies of the views loaded by xib (UITableViews, UILabels, OHAttributedLabels), of the data structures inside it, and so on. Therefore I usually start my heapshot analysis by searching for some instances of a UIViewController or of a subclass of it. Many times the controller is not released correctly due to circular strong references.
Obviously, I assumed you are able to use heapshots. If not, take a look here: http://useyourloaf.com/blog/2011/03/08/using-heapshots-to-find-abandoned-memory.html

**Comment by coppercash** [comment]
It seems we are in two different situation. Thanks all the same. Article about heapshot help a lot.
