### ISSUE TITLE
Feature Request: parse HTML into NSAttributedString

### ISSUE THREAD

**Issue by newacct** [AliSoftware/OHAttributedLabel#88]
So that we don't have to construct the NSAttributedString painstakingly from scratch. At least a few simple tags, like B, I, U, A,

**Comment by AliSoftware** [comment]
Done!

I built the system so that it is easy to add support for new tags, and that is also easy to support multiple tag systems (I currently created parsers for both HTML and a simple markup, for example) :-)

This is open to improvements of course, like adding some other tags.

---

Note that adding support for links (and `<a href=...>...</a>` tags) is unfortunately not straightforward, and thus not yet implemented, as there is no official CoreText attribute key for links ([see the CT attributes doc](https://developer.apple.com/library/mac/#documentation/Carbon/Reference/CoreText_StringAttributes_Ref/Reference/reference.html#//apple_ref/doc/uid/TP40005303)).

This is doable anyway, but to implement it we would have to use a custom attribute key to store the link attribute information in our `NSAttributedString` (or use the one used by UIKit if we can find it… maybe the same `NSLinkAttributeKey` constant that is used in OSX/AppKit?), and then make the `OHAttributedLabel` class aware of this custom attribute, so that it is able to interpret it correctly and display the link.

_Unfortunately, I don't think I will have time to add this specific custom attribute support just for this soon… but of course feel free to implement yourself in a fork and propose a pull request :-P_

**Comment by AliSoftware** [comment]
Late note: [Version 3.2.0](https://github.com/AliSoftware/OHAttributedLabel/tree/3.2.0), released 2 month ago (commit 78b2ff4f0b9805f65afc648fa09878a94cfb98ae), did add support for links in `NSAttributedString` and adds markup for links in both `OHASBasicHTMLParser` and `OHASBasicMarkupParser`.
