### ISSUE TITLE
iOS6 Deployment target causes crash when library is run on iOS 5 or older devices

### ISSUE THREAD

**Issue by LefterisHaritou** [AliSoftware/OHAttributedLabel#93]
The crash that happens is this:
Symbol not found: _objc_setProperty_nonatomic

and it is caused by the higher deployment target of the library.

I'm not getting it, why the deployment target of the library is set to iOS 6, when you are not using anything related to iOS 6 in your code.
The deployment target should be the minimum deployment target in which the library can compile and run successfully

**Comment by AliSoftware** [comment]
I tried running the example project in the iOS5 simulator with no crash.
_(I forgot to set the Deployment target int the library as generally only the one of the application is relevant, but yes I'll set it to 4.3)_

**Comment by LefterisHaritou** [comment]
Well, I'm using the addCustomLink method and as soon as someone clicks on a link on the label, it causes the above crash.

If you look it up in SO, you will see it's caused when app's deployment target vs library deployment target is lower:
http://stackoverflow.com/questions/12641190/arc-app-crashes-when-accessing-property-form-arc-static-lib

**Comment by AliSoftware** [comment]
Ok thanks.

Compiling the library using ARC would have solved the problem (as the `OHAttributedLabel` code is compatible with both MRC and ARC).

PS : probably linking with the `-fobjc-arc` _linker_ flag may have fixed that too (especially if your application itself is MRC and not ARC). I should probably change the default settings of the library back to MRC to make sure the library does not need the ARC runtime and is compatible with _both_ MRC and ARC applications…
_(not sure if Xcode adds the ARC specific runtime methods automatically if the application is MRC, it does if the app is using ARC, and should do it too if one of the library is using ARC even if the app is MRC, but not sure it detects that specific case)_

I fixed the library deployment target anyway in my latest commit so that should be OK now.
