### ISSUE TITLE
the texts after emoji is getting bold.

### ISSUE THREAD

**Issue by xuantungsp** [AliSoftware/OHAttributedLabel#94]
the texts after emoji is getting bold.
How to resolve issue?

http://imageshack.us/a/img6/2717/screenshot20121101at433.png

**Comment by AliSoftware** [comment]
This is probably not because of the emojis but because of the font you use.

Some CoreText fonts provided by Apple have some unicode characters/glyphs (like Chinese characters and the ones in your capture) that are designed this way taht they seem bolder than the rest of the glyphs. This is not always the bold variant of the font but rather the way these particular glyphs are designed in the CoreText font.

Try using a different font and see if the appearance of these specific characters are thiner.  
_Or try different characters or remove emojis to confirm that it is related to these particular characters in this CoreText font and not related to the presence of emojis before._

**Comment by xuantungsp** [comment]
this issue only occur on ios 6.

I change system font to  STHeitiTC-Light font. the text (japanese) after emojis don't get bold. but latin text is very ugly.

**Comment by xuantungsp** [comment]
instagram have issue like that. 
thank for support.

**Comment by AliSoftware** [comment]
Yes and that confirms my hypothesis regarding the reason being the CoreText Apple fonts themselves ;-)
You may issue a big report to Apple for this one I guess.
