### ISSUE TITLE
Error at OHAttributedLabel.h

### ISSUE THREAD

**Issue by VuTrongQuy** [AliSoftware/OHAttributedLabel#95]
typedef CF_OPTIONS(int32_t, OHBoldStyleTrait)
{
    kOHBoldStyleTraitMask       = 0x030000,
    kOHBoldStyleTraitSetBold    = 0x030000,
    kOHBoldStyleTraitUnSetBold  = 0x020000,
} ;

Error here,

**Comment by AliSoftware** [comment]
??? What error do you have? I don't have enough info to help you here…

Are you at least using the latest Xcode and LLVM compiler?

**Comment by VuTrongQuy** [comment]
Sr, check my image : http://www.mediafire.com/?43d5akrvt893ykd,3canc3v37y9clk9,pjlrjdt9mfkdd68

http://i50.tinypic.com/rtde7t.png
http://i49.tinypic.com/24xpdi0.png

**Comment by AliSoftware** [comment]
Yes so that's what I suspected, your version of Xcode / LLVM is too old.

`NS_OPTIONS` and `CF_OPTIONS` macros are  defined in the Objective-C Runtime headers, so if your compiler/Xcode can't find them it means your Xcode is not up-to-date.

I just did a commit to fix cases for old Xcode versions, so that should be compatible now.
But anyway, **you should really update your Xcode version**. The LLVM compiler is much better (detect more potential errors and warnings, optimize your code, etc) and is compatible with modern Objective-C and so on.

**Comment by VuTrongQuy** [comment]
i use x-code 4.4.1 :)

**Comment by AliSoftware** [comment]
Then you should update to Xcode 4.5.2 ;)

**Comment by danielgindi** [comment]
Which is too old. Current version is 4.5.2.

נשלח מה-iPhone שלי

ב-8 בנוב 2012, בשעה 17:54, VuTrongQuy notifications@github.com כתב/ה:

**Comment by VuTrongQuy** [comment]
Ok, thanks :+1:

**Comment by VuTrongQuy** [comment]
Dear AliSoftware,
Why OHAttributedLabel not support number line of label ( in uitableviewcell ) > 1 ?

**Comment by AliSoftware** [comment]
https://github.com/AliSoftware/OHAttributedLabel/issues/3

**Comment by VuTrongQuy** [comment]
why u don't try upgrade ur code to support this.

**Comment by AliSoftware** [comment]
o_O You're kidding, right?
And why don't you do it yourself and post me a pull request when you're done?
- I give this code for free to the community but that's not my job and I don't have time for everyone. Except if you consider paying me for this?
- Did you even read the whole issue #3, and all the details why this is a very very complex problem? Especially the whole explanations I give about CoreText not supporting this constraint natively?
- There is already plenty of NSLog warnings printed in the console when you run your application and encounter this known issue, explain what is the problem, and quote the issue to have all the info… but I bet you didn't take time to read those warnings either?
- As there is already a full discussion about it in the other issue #3, why do you continue talking _here_ about a completely different matter than the one you opened this issue #95 for?

And by the way, this issue is not the place to talk about this, as there is already a dedicated issue for that with the full discussion about all the aspects, so please don't mess with the GitHub issue system and mix different subjects in the same issue (that a hell for other users to follow .

**Comment by VuTrongQuy** [comment]
Sr and thanks ur support. Close topic here :+1:
