### ISSUE TITLE
Difference between OHAttributedLabel and UILabel with standart fonts

### ISSUE THREAD

**Issue by e5faf2** [AliSoftware/OHAttributedLabel#96]
With Arial 15 font, OHAttributedLabel have difference with UILabel. On OHAttributedLabel text displays with scaled spaces between characters and different characters line spacing.

Compare: up - UILabel, down - OHAttributedLabel
![Compare: up - UILabel, down - OHAttributedLabel](http://gyazo.com/64e64f62312ad614fc463ad753f7681a.png?1352449816)

**Comment by AliSoftware** [comment]
I'm afraid we can't do much about it.
AFAIK, the reason for this difference is because UILabel uses UIKit and UIFonts to draw text and OHAttributedLabel uses CoreText and CTFonts. And there is a slight difference between the two Apple implementations and font versions of these two Apple frameworks (you may issue a bug report to Apple anyway if you feel like it)
