### ISSUE TITLE
Touching the right hand side of a single character with an embedded link doesn't work.

### ISSUE THREAD

**Issue by Infiniverse** [AliSoftware/OHAttributedLabel#99]
- Touch and hold a single character link on the left hand side of the character and it selects the link.
- Touch and hold a single character link on the right hand side and it doesn't! It should!

http://www.josef-k.net/misc/dots/github/image.jpg
http://www.josef-k.net/misc/dots/github/image2.jpg

**Comment by Infiniverse** [comment]
This could be related to #55.

**Comment by Infiniverse** [comment]
Ok, I've found the problem. It's because CTLineGetStringIndexForPosition doesn't locate the position of a point within a string, instead what it does is locate the index of the string at which to place the cursor. This is why the apparent 1/2 character offset on selection.

The fix is simple. Having found the selection offset into the string, we then look up the start coordinate of that glyph. If the selection point is before that coordinate then it must have been the case that the user was actually clicking on the character before. 

Joe

The following patch fixes it:

<pre>===================================================================
--- Libraries/OHAttributedLabel/OHAttributedLabel.m (date 1352666352000)
+++ Libraries/OHAttributedLabel/OHAttributedLabel.m (revision )
@@ -333,6 +333,11 @@
            CGPoint relativePoint = CGPointMake(point.x-CGRectGetMinX(lineRect),
                                                point.y-CGRectGetMinY(lineRect));
            CFIndex idx = CTLineGetStringIndexForPosition(line, relativePoint);
+           CGFloat glyphStart;
+           CTLineGetOffsetForStringIndex(line, idx, &glyphStart);
+           if (relativePoint.x &lt; glyphStart && idx) {
+               --idx;
+           }
            link = ([self linkAtCharacterIndex:idx]);
            if (link) return link;
        }
</pre>

**Comment by AliSoftware** [comment]
Cool, thanks for your investigation!

I'll try and test it ASAP to patch the master branch.

Thx

**Comment by AliSoftware** [comment]
Can you explain why you use the _secondary offset_ returned by `CTLineGetOffsetForStringIndex` (the one passed and returned by reference in the third parameter) instead of the _primary offset_ (the one directly returned by the function) to check if the index correspond to the next or current character?

The primary offset should be sufficient, right? (I have to admit that I don't really understand in which case there can be a _secondary_ offset, actually)

**Comment by Infiniverse** [comment]
Probably for no real reason. I'm not all that familiar with the API.

Joe

## 

Dr Joe Karthauser

**Comment by AliSoftware** [comment]
Ok! So I used the primary position directly returned by the function, that's easier to use and more understandable to read.

I've applied the fix to the master branch. Version 3.1.1 of `OHAttributedLabel` now include the fix for this (we are already at version 3.2.0 now)

I think that the only case when we have a primary AND a secondary offset is when the text is written in italics. In that case, the top and the bottom of the carret to draw are at slightly different x positions, because of the italics. That's the only case I think of for which there would be a secondary position different from the primary one. But I'm only guessing.
